-- CreateTable
CREATE TABLE `Performance_appraisal_result_supervisor_review` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `supervisor_email` VARCHAR(255) NOT NULL,
    `employee_email` VARCHAR(255) NOT NULL,
    `status` VARCHAR(255) NOT NULL,
    `appraisal_year` INTEGER NOT NULL,
    `total_point` INTEGER NULL,
    `average_point` FLOAT NULL,
    `answerCategory1Example1` INTEGER NULL,
    `answerCategory1Example2` INTEGER NULL,
    `answerCategory1Example3` INTEGER NULL,
    `answerCategory1Example4` INTEGER NULL,
    `answerCategory1Example5` INTEGER NULL,
    `answerCategory2Example1` INTEGER NULL,
    `answerCategory2Example2` INTEGER NULL,
    `answerCategory2Example3` INTEGER NULL,
    `answerCategory2Example4` INTEGER NULL,
    `answerCategory2Example5` INTEGER NULL,
    `answerCategory3Example1` INTEGER NULL,
    `answerCategory3Example2` INTEGER NULL,
    `answerCategory3Example3` INTEGER NULL,
    `answerCategory3Example4` INTEGER NULL,
    `answerCategory3Example5` INTEGER NULL,
    `answerCategory4Example1` INTEGER NULL,
    `answerCategory4Example2` INTEGER NULL,
    `answerCategory4Example3` INTEGER NULL,
    `answerCategory4Example4` INTEGER NULL,
    `answerCategory4Example5` INTEGER NULL,
    `answerCategory5Example1` INTEGER NULL,
    `answerCategory5Example2` INTEGER NULL,
    `answerCategory5Example3` INTEGER NULL,
    `answerCategory5Example4` INTEGER NULL,
    `answerCategory5Example5` INTEGER NULL,
    `answerCategory6Example1` INTEGER NULL,
    `answerCategory6Example2` INTEGER NULL,
    `answerCategory6Example3` INTEGER NULL,
    `answerCategory6Example4` INTEGER NULL,
    `answerCategory6Example5` INTEGER NULL,
    `answerCategory7Example1` INTEGER NULL,
    `answerCategory7Example2` INTEGER NULL,
    `answerCategory7Example3` INTEGER NULL,
    `answerCategory7Example4` INTEGER NULL,
    `answerCategory7Example5` INTEGER NULL,
    `answerCategory8Example1` INTEGER NULL,
    `answerCategory8Example2` INTEGER NULL,
    `answerCategory8Example3` INTEGER NULL,
    `answerCategory8Example4` INTEGER NULL,
    `answerCategory8Example5` INTEGER NULL,
    `answerCategory9Example1` INTEGER NULL,
    `answerCategory9Example2` INTEGER NULL,
    `answerCategory9Example3` INTEGER NULL,
    `answerCategory9Example4` INTEGER NULL,
    `answerCategory9Example5` INTEGER NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Performance_appraisal_result_comment_supervisor_review` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `supervisor_email` VARCHAR(255) NOT NULL,
    `employee_email` VARCHAR(255) NOT NULL,
    `appraisal_year` INTEGER NOT NULL,
    `userCommentCategory1Example1` TEXT NULL,
    `userCommentCategory1Example2` TEXT NULL,
    `userCommentCategory1Example3` TEXT NULL,
    `userCommentCategory1Example4` TEXT NULL,
    `userCommentCategory1Example5` TEXT NULL,
    `userCommentCategory2Example1` TEXT NULL,
    `userCommentCategory2Example2` TEXT NULL,
    `userCommentCategory2Example3` TEXT NULL,
    `userCommentCategory2Example4` TEXT NULL,
    `userCommentCategory2Example5` TEXT NULL,
    `userCommentCategory3Example1` TEXT NULL,
    `userCommentCategory3Example2` TEXT NULL,
    `userCommentCategory3Example3` TEXT NULL,
    `userCommentCategory3Example4` TEXT NULL,
    `userCommentCategory3Example5` TEXT NULL,
    `userCommentCategory4Example1` TEXT NULL,
    `userCommentCategory4Example2` TEXT NULL,
    `userCommentCategory4Example3` TEXT NULL,
    `userCommentCategory4Example4` TEXT NULL,
    `userCommentCategory4Example5` TEXT NULL,
    `userCommentCategory5Example1` TEXT NULL,
    `userCommentCategory5Example2` TEXT NULL,
    `userCommentCategory5Example3` TEXT NULL,
    `userCommentCategory5Example4` TEXT NULL,
    `userCommentCategory5Example5` TEXT NULL,
    `userCommentCategory6Example1` TEXT NULL,
    `userCommentCategory6Example2` TEXT NULL,
    `userCommentCategory6Example3` TEXT NULL,
    `userCommentCategory6Example4` TEXT NULL,
    `userCommentCategory6Example5` TEXT NULL,
    `userCommentCategory7Example1` TEXT NULL,
    `userCommentCategory7Example2` TEXT NULL,
    `userCommentCategory7Example3` TEXT NULL,
    `userCommentCategory7Example4` TEXT NULL,
    `userCommentCategory7Example5` TEXT NULL,
    `userCommentCategory8Example1` TEXT NULL,
    `userCommentCategory8Example2` TEXT NULL,
    `userCommentCategory8Example3` TEXT NULL,
    `userCommentCategory8Example4` TEXT NULL,
    `userCommentCategory8Example5` TEXT NULL,
    `userCommentCategory9Example1` TEXT NULL,
    `userCommentCategory9Example2` TEXT NULL,
    `userCommentCategory9Example3` TEXT NULL,
    `userCommentCategory9Example4` TEXT NULL,
    `userCommentCategory9Example5` TEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Performance_appraisal_final_result` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `employee_id` VARCHAR(255) NOT NULL,
    `supervisor_email` VARCHAR(255) NOT NULL,
    `approved_by` VARCHAR(255) NOT NULL,
    `approved_status` VARCHAR(255) NOT NULL,
    `evaluation_year` INTEGER NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
